version: '3.8'
services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    environment:
      - MTX_RTSPTRANSPORTS=tcp
      - MTX_WEBRTCADDITIONALHOSTS=192.168.x.x
    ports:
      - "8554:8554"       # RTSP
      - "1935:1935"       # RTMP
      - "8888:8888"       # HTTP (HLS, API, etc.)
      - "8889:8889"       # HTTPS (HLS, API, etc.)
      - "8890:8890/udp"   # WebRTC (UDP)
      - "8189:8189/udp"   # SRT (UDP)
#    restart: unless-stopped