services:

  mediamtx:
    image: rg.fr-par.scw.cloud/protecia/mediamtx:${IMAGE_TAG}
    container_name: mediamtx
    environment:
      - MTX_RTSPTRANSPORTS=tcp
      - MTX_WEBRTCADDITIONALHOSTS=mtx.protecia.net
    volumes:
      - /home/mediamtx/deploy/mediamtx.yaml:/mediamtx.yml
    labels:
      - "traefik.http.services.mediamtx.loadbalancer.server.port=8889"
      - "traefik.http.routers.mediamtx.entrypoints=webrtc"
      - "traefik.http.routers.mediamtx.tls=true"
      - "traefik.http.routers.mediamtx.tls.certresolver=myresolver"
      - "traefik.http.routers.mediamtx.rule=Host(`mtx.protecia.net`)"
      - "traefik.docker.network=compose_traefik_aratech_net"
    ports:
      - "8554:8554"       # RTSP
      - "8889:8889"       # WEB RTC
      - "8189:8189/udp"   # WEB RTC
    networks:
      compose_traefik_aratech_net:
        ipv4_address: 10.5.5.110

networks:
  compose_traefik_aratech_net:
    external: true
