services:

  mediamtx:
    image: rg.fr-par.scw.cloud/protecia/mediamtx:${IMAGE_TAG}
    container_name: mediamtx
    environment:
      - MTX_RTSPTRANSPORTS=tcp
      - MTX_WEBRTCADDITIONALHOSTS=mtx.protecia.net
    volumes:
      - /home/mediamtx/deploy/mediamtx.yaml:/mediamtx.yml
#    labels:
#      - "traefik.http.services.django-protecia.loadbalancer.server.port=80"
#      - "traefik.http.routers.django-protecia_http.entrypoints=web"
#      - "traefik.http.routers.django-protecia_http.rule=Host(`dev.protecia.com`)"
#      - "traefik.http.routers.django-protecia_http.middlewares=protecia_https"
#      - "traefik.http.middlewares.protecia_https.redirectscheme.scheme=https"
#      - "traefik.http.routers.django-protecia.entrypoints=websecure"
#      - "traefik.http.routers.django-protecia.rule=Host(`dev.protecia.com`)"
#      - "traefik.http.routers.django-protecia.tls=true"
#      - "traefik.http.routers.django-protecia.tls.certresolver=myresolver"
#      - "traefik.http.middlewares.vitrineHeader.headers.customrequestheaders.HTTP_X_FORWARDED_PROTO=https"
    ports:
      - "8554:8554"       # RTSP
      - "8889:8889"       # WEB RTC
      - "8189:8189/udp"   # WEB RTC
    networks:
      compose_traefik_aratech_net:
        ipv4_address: 10.5.5.110

networks:
  compose_traefik_aratech_net:
    external: true
