services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    environment:
      - MTX_RTSPTRANSPORTS=tcp
      - MTX_WEBRTCADDITIONALHOSTS=<public ip adress>>
    ports:
      - "8554:8554"       # RTSP
      - "1935:1935"       # RTMP
      - "8888:8888"       # HTTP (HLS, API, etc.)
      - "8889:8889"       # HTTPS (HLS, API, etc.)
      - "8890:8890/udp"   # WebRTC (UDP)
      - "8189:8189/udp"   # SRT (UDP)
      - "9997:9997"
    volumes:
      - ./mediamtx.yaml:/mediamtx.yml
#    restart: unless-stopped
